### PR TITLE
Update dom parsing and fix some elements not bolded and broken buttons

### LINKED ISSUE #27: Does not work for Facebook
The extension does not seem to work on Facebook - only the names of commenters get affected sometimes, but never the comments or posts themselves. Is this behaviour expected? 

Thanks a lot.

### LINKED ISSUE #36: Gmail hit or miss
It really seems to depend on the font used, Some bits of text in Gmail it works on and other bits It doesn't Even within the message.

### LINKED ISSUE #43: left and right buttons break after clicking on this page with extension toggled
https://www.solidjs.com/tutorial/bindings_events

Reproduce by clicking on the left and right arrows. Notice that the buttons stop working if the tool is toggled. Turning off the toggle for this reader fixes the issue. 

image

### LINKED ISSUE #57: Don't process text in code block.
For example:

- https://docs.tendermint.com/master/tendermint-core/consensus/reactor.html#reactor

### LINKED ISSUE #87: the videos in BILIBILI.com lose picture, only sound
#### Runtime Environment

- Windows 10 Build 19044.1526
- Chrome 102.0.5005.63 --- x64 
- Jiffy Reader 1.0.0

#### Current Behavior
**turn on bionic-reading, the videos in BILIBILI.com lose picture, only sound.** 

image-20220529111720855

### PR DESCRIPTION
**Pull request by asieduernest12**
@X140Yu @ansh kindly take a look

fixes #71 
#45 
fixed #57 
before
Screenshot from 2022-05-28 13-39-25

after
Screenshot from 2022-05-28 13-39-04

fix #55 
fix #43 reporter should test this 
fix #36 
fix #27 only for elements already on the screen. elements loaded dynamically through js are not bolded
fix #87

### CODE REVIEW

**Comment by ansh** [comment]
Can you please contact me? @asieduernest12 My email is anshnanda10@gmail.com

File: src/ContentScript/index.js [hunk 1]
```diff
@@ -57,11 +59,12 @@ const ToggleReading = (enableReading) => {
 
   if (boldedElements.length < 1) {
     addStyles();
-    parseDocument();
+    [...document.body.children].flatMap((child) => [...child.childNodes]).forEach(parseNode);
```
Comment (X140Yu) [inline src/ContentScript/index.js:62]: maybe this is good enough?

```suggestion
    [...document.body.children].forEach(parseNode);
```

**Comment by X140Yu** [comment]
@asieduernest12 LGTM, but there are some conflicts, you can resolve first and try to merge yourself

**Review by X140Yu — APPROVED** [review]
